#!/bin/bash
# This hook is sourced after a new virtualenv is activated.
pip install ipython ipdb tox pre-commit bbm-wrench && pre-commit install
if [ -f "$file" ]
then 
	pip install -r requirements.txt
fi
